### ISSUE TITLE
supy.util.gen_epw: AttributeError

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/SuPy#18]
Hi Developers,

I've tried to generate an epw file with supy.util.gen_epw, but I get an AttributeError: 'MultiIndex' object has no attribute 'year'. Attached are input and output files from my test run.
[R11a01.zip](https://github.com/UMEP-dev/UMEP/files/5792621/R11a01.zip)

If somebody could take a look at it, what would be great. Thank you in advance!
Csilla

**Comment by CsillaVG** [comment]
Hi again,

I am sorry for the belated feedback. The problem was on my end... I had a single grid test run and tried the send the entire output (df_output) from SuPy  to gen_epw. 
For a correct hourly epw file one needs to use df_output.loc[grid, 'SUEWS'].resample('h').nearest() subset instead of the entire df_output.

I am sorry for the troubles. It makes sense in retrospect :)

**Comment by sunt05** [comment]
Thanks for the update/fix 👍🏼
