### ISSUE TITLE
Setting different irrigation settings for different years

### ISSUE THREAD

**Issue by oliver-michels** [UMEP-dev/SuPy#20]
Dear Ting

Since last weekend most of my issues with running the model have been solved. I did come across a new issue, which could come up for other researches in the future as well regarding irrigation settings.

I am currently modelling irrigation over a period of ten years in Vancouver. Over this time period there have been different water use restrictions in place depending on the severity of drought and heat that year, e.g. watering only on odd days, watering only during certain hours or, for short periods of time, complete watering bans. 

I am wondering if there is a way to set up multiple watering restriction scenarios in SuPy current state?

note: I have found the options, to set beginning and end of irrigation, fractions of properties that use irrigation and to turn on and of irrigation depending on weekdays, but this only applies to the entire simulation period and not for a specific short term period.

Kind regards

**Comment by sunt05** [comment]
Thanks @oliver-michels for bringing up this issue.
Actually your application scenario is right where SuPy could shine!

This can be fairly easily resolved this way:
say you have two irrigation operational schedules, `irr1` and `irr2`, which shall be rotated in your simulation period when irrigation should apply.
then for the first `irr1` period specified by `df_forcing_1`, do this:
```
df_state_1=f(df_state_init, opt_irr1)
df_output1,df_state_1_end=sp.run_supy(df_forcing_1, df_state_1)
```
next, update `df_state_1_end` with your `irr2` options and run the next period specified by `df_forcing_2`:
```
df_state_2=f(df_state_1_end, opt_irr2)
df_output2,df_state_2_end=sp.run_supy(df_forcing_2, df_state_2)
```
similarly, repeat the steps above and collect the `df_output_{x}` (where `{x}` is your x-th simulation sub-period).

Hope the above helps.
