### ISSUE TITLE
check_forcing: relax ranges of variables?

### ISSUE THREAD

**Issue by matthiasdemuzere** [UMEP-dev/SuPy#23]
**Describe the Issue**
I am testing supy over Mexico City, using input from ERA5. When running applying `check_forcing`, I got this warning:
`"pres" should be between [800, 1300] but "758.7" is found at 2020-04-30 23:05:00`

Perhaps the range should be a bit more relaxed, as such low pressure values might be valid, especially for high-altitude regions? 

Moreover, as you can see from the timeseries below, seems that only one timestep is reported, even though the whole time series has pressure values < 800 hPa? Not sure if this behaviour is intended?

**Location**
Referring to the following:

https://github.com/UMEP-dev/SuPy/blob/100d93bedfb2b9d954c479add1ff4b65aa7cd0b9/src/supy/checker_rules_indiv.json#L996-L1004

**Screenshots**
![image](https://user-images.githubusercontent.com/6926916/106506219-b30b5300-64c9-11eb-9ad8-c112d6ea3e74.png)

**Additional context**
Not applicable

**Comment by sunt05** [comment]
Thanks @matthiasdemuzere for reporting this issue.
Yes, I fully agree with you that the criteria used in the checking procedure should be improved: the current values were directly borrowed from UMEP; maybe we should determine these more carefully by examination of a broader range of observations.

**Comment by sunt05** [comment]
fixed by https://github.com/UMEP-dev/SuPy/commit/d01c8c208d526a623f1683f59796419d52841874
