### ISSUE TITLE
sp.util.gen_forcing_era5 -- AttributeError: 'Dataset' object has no attribute 'z'

### ISSUE THREAD

**Issue by LewisB7** [UMEP-dev/SuPy#33]
**Describe the Issue**
AttributeError: 'Dataset' object has no attribute 'z'

**Location**
-> 1096     da_gph_sfc = ds_sfc.z

**Screenshot**

![error](https://user-images.githubusercontent.com/22103045/126632561-85fcc035-971b-44c8-8779-7ae3b6f8b26e.JPG)

**Comment by sunt05** [comment]
fixed in ver 2021.7.22
