### ISSUE TITLE
Supy vs SUEWS advanced outputs

### ISSUE THREAD

**Issue by DimitrisTsi** [UMEP-dev/SuPy#41]
Hello!
I am having issues replicating the same results using SUEWS advanced from umep and SuPy from a jupyter notebook.
In the zipped file i have included i) the outputs of SUEWS Prepare from UMEP which are used to run suews and ii) the outputs of the model using SUEWS Advanced in UMEP (version 3.17.3).

Then, using the RunControl.nml file located in the output folder, i use SuPy (version 2021.1.12) through a Jupyter Notebook without making any changes in the inputs. After examining the model runs observe differences in the UEB components ('QN','QF','QS','QE','QH') which i am interested in.

For example using the command 
df_output.loc[1]['SUEWS'][['QN','QF','QS','QE','QH']].resample('60min').mean().iloc[721:-743].describe().round(1) 
i get the table shown in image 1, while the original output file from suews in umep gives the table shown in image 2.
I have double checked that the intervals (721:-743) are the same for the outputs.

What am i missing?
[in_out_suews.zip](https://github.com/UMEP-dev/SuPy/files/7617831/in_out_suews.zip)
image1
![image1](https://user-images.githubusercontent.com/20373671/143860413-7d92c666-7bb0-4e3b-aa2c-9c2215a998b3.png)
image2
![image2](https://user-images.githubusercontent.com/20373671/143860421-eb304a7f-9d00-4a18-8308-8ee8024004ad.png)
 Thanks in advance!

**Comment by sunt05** [comment]
Hi @DimitrisTsi,

 it could be the SuPy version is different between the UMEP and your installation used in jupyter notebook.
To double-check the SuPy version, please use
```
import supy as sp
sp.show_version()
```
in UMEP's python console.

**Comment by DimitrisTsi** [comment]
Thanks @sunt05 
I checked and the version is 2020.7.8dev
So i will update and re-check the outputs!
