### ISSUE TITLE
Daily maximum temperature from DailyState

### ISSUE THREAD

**Issue by nabihah-ghufoor** [UMEP-dev/SuPy#50]
**Describe the Issue**
Incorrect daily maximum temperatures from DailyState.

Model was run with 5 grids (each with different albedo: 0.1, 0.3, 0.5, 0.7 and 0.9). When looking at the  difference between max daily temperatures (Tmax from DailyState) the temperature difference was 0 for all albedo values. 

I then extracted maximum daily temperature from the SUEWS output (using max T2 value and resampling for daily values). This showed that there was a temperature difference between the different albedo's maximum temperatures. The max daily temperatures were hotter for low albedo and cooler for high albedo as expected so I am sure that the albedo values were set-up correctly in df_state_init.

**Location**

**Screenshots**

Max daily temperature when extracted from SUEWS: 
![image](https://user-images.githubusercontent.com/95298191/172900584-6526b348-ab06-485c-8d39-f467f25eb1f6.png)
Max daily temperature from Daily state:
![image](https://user-images.githubusercontent.com/95298191/172900718-78e27dad-caa9-4f6b-ab7b-92e20f597dd3.png)

[GLA_study.zip](https://github.com/UMEP-dev/SuPy/files/8872312/GLA_study.zip)

**Additional context**

I have attached the .pkl for the df_state_init and df_forcing I used in the model

**Comment by sunt05** [comment]
Sorry this was not clarified in the description of `dailystate` output group: the `Tmax` refers to the daily maximum value in the forcing data, so the values of all grids are the same.

Now this has been clarified in the documentation:
https://suews.readthedocs.io/en/latest/output_files/output_files.html#ssss-dailystate-txt
