### ISSUE TITLE
ERA5 pressure data

### ISSUE THREAD

**Issue by CsillaVG** [UMEP-dev/SuPy#53]
Hi!

As a finger practice, I've download and generate standard SuPy forcing from ERA5 data for a given location but for different elevations (2m, 10m, 50m and 100m) using SuPy's utility function (gen_forcing_era5). I get a pressure data that increases with elevation. It's either the heatwave or a bug of some sort. :)

Environment info:
macOS 11.5.1
supy: 2022.4.7 
supy_driver: 2021a5

Here is what I see (hope it goes through):
![dSuPy_forcing-3_2_ERA5s_PSzL2](https://user-images.githubusercontent.com/53008258/179776443-a815b11e-c46e-4090-a957-ae4890e55cc5.png)

Let me know if additional info is needed.
Thank you and stay hydrated!
Csilla

**Comment by sunt05** [comment]
Thanks @CsillaVG - hope you are staying cool!

This sees to be bug in the supy ERA5 utility - I'll fix it shortly.
