### ISSUE TITLE
What package versions are required for newest supy version?

### ISSUE THREAD

**Issue by mmcgrory** [UMEP-dev/SuPy#60]
Is this documented anywhere?

**Comment by sunt05** [comment]
This is specified in the [`setup.py` file](https://github.com/UMEP-dev/SuPy/blob/ad470a3752a2bd68386d3ff3f293d453be2a5a64/src/setup.py#L53-L70) for packaging the supy code, which users are not supposed to directly deal with - in case any problem occurs on your system, please raise a separate issue with detailed error report and I will handle those.
Thanks!
