### ISSUE TITLE
Windows fatal exception: code 0xc0000028-Error2 -when Running SUEWS Advance in QGIS 

### ISSUE THREAD

**Issue by ozyaz** [UMEP-dev/SuPy#64]
Hello UMEP community,

shortly after running advanced succesfully with one month meteodata and 121 grid cells, I needed to extend my area to 1x1km , 400 grids with 50m resolution. I did the analysis again and run the SUEWS prepare succesfully, later for the Advanced QGIS keep crashing on different computers. This is the error I have, never had this one before:)
is it maybe about the area lenght, what is the recommended lenght of the area and resolution for SUEWS?

my meteo data is for a month, I even tried with a week to reduce the calculation time and effort.

----

```
Python Stack Trace
Windows fatal exception: code 0xc0000028
 
Current thread 0x00001b60 (most recent call first):
  File "C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy\_run.py", line 121 in suews_cal_tstep_multi
    res_suews_tstep_multi = sd.suews_cal_multitsteps(**dict_input)
  File "C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy\_run.py", line 370 in 
    suews_cal_tstep_multi(input_grid, df_forcing)
  File "C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy\_run.py", line 369 in run_supy_ser
    list_res = [
  File "C:\Users\ozgey\AppData\Roaming\Python\Python39\site-packages\supy\_supy_module.py", line 370 in run_supy
    df_output, df_state_final = run_supy_ser(
  File "C:\Users/ozgey/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\suews_wrapper.py", line 68 in wrapper
    df_output, df_state_final = sp.run_supy(df_forcing, df_state_init, check_input=True, serial_mode=True)
  File "C:\Users/ozgey/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWS\suews.py", line 314 in start_progress
    suews_wrapper.wrapper(self.model_dir, self.iface)
  File "C:\Users/ozgey/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWS\suews.py", line 158 in run
    self.dlg.exec_()
  File "C:\Users/ozgey/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\UMEP.py", line 440 in SUEWS_advanced
    sg.run()
 
 
Stack Trace
No stack trace is available.
```
 
QGIS Info
QGIS Version: 3.26.1-Buenos Aires
QGIS code revision: b609df9ed4d
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/100167079/186374082-ca336168-d721-413b-9e53-869f4ae6837f.png)

**Additional context**
the input data created with UMEP-SUEWS in QGIS:
[ber1km_2019_data_60.txt](https://github.com/UMEP-dev/SuPy/files/9414526/ber1km_2019_data_60.txt)
[SUEWS_WithinGridWaterDist.txt](https://github.com/UMEP-dev/SuPy/files/9414545/SUEWS_WithinGridWaterDist.txt)
[int_2019_data_60.txt](https://github.com/UMEP-dev/SuPy/files/9414546/int_2019_data_60.txt)
[SUEWS_AnthropogenicEmission.txt](https://github.com/UMEP-dev/SuPy/files/9414547/SUEWS_AnthropogenicEmission.txt)
[SUEWS_BiogenCO2.txt](https://github.com/UMEP-dev/SuPy/files/9414548/SUEWS_BiogenCO2.txt)
[SUEWS_Conductance.txt](https://github.com/UMEP-dev/SuPy/files/9414549/SUEWS_Conductance.txt)
[SUEWS_ESTMCoefficients.txt](https://github.com/UMEP-dev/SuPy/files/9414550/SUEWS_ESTMCoefficients.txt)
[SUEWS_Irrigation.txt](https://github.com/UMEP-dev/SuPy/files/9414551/SUEWS_Irrigation.txt)
[SUEWS_NonVeg.txt](https://github.com/UMEP-dev/SuPy/files/9414552/SUEWS_NonVeg.txt)
[SUEWS_OHMCoefficients.txt](https://github.com/UMEP-dev/SuPy/files/9414553/SUEWS_OHMCoefficients.txt)
[SUEWS_Profiles.txt](https://github.com/UMEP-dev/SuPy/files/9414554/SUEWS_Profiles.txt)
[SUEWS_SiteSelect.txt](https://github.com/UMEP-dev/SuPy/files/9414555/SUEWS_SiteSelect.txt)
[SUEWS_Snow.txt](https://github.com/UMEP-dev/SuPy/files/9414556/SUEWS_Snow.txt)
[SUEWS_Soil.txt](https://github.com/UMEP-dev/SuPy/files/9414557/SUEWS_Soil.txt)
[SUEWS_Veg.txt](https://github.com/UMEP-dev/SuPy/files/9414559/SUEWS_Veg.txt)
[SUEWS_Water.txt](https://github.com/UMEP-dev/SuPy/files/9414560/SUEWS_Water.txt)

**Comment by sunt05** [comment]
Sorry to see this - any other error info from supy?
