### ISSUE TITLE
[Docs]data-structure/df_state

### ISSUE THREAD

**Issue by RussellGl** [UMEP-dev/SuPy#74]
## Issue
I have come across several df_state parameters which are not consistent with what is on the documentation:
https://supy.readthedocs.io/en/latest/data-structure/df_state.html

'sfr' should be 'sfr_surf'
'soilstorecap' should be 'soilstorecap_surf'
'soilstore_id' should be 'soilstore_surf'

SuPy versions I am using:
-------------
supy: 2022.9.22
supy_driver: 2021a14.post3

Thank you,
Russell

## Links
[source doc](https://github.com/UMEP-dev/SuPy/blob/master/docs/source/data-structure/df_state.rst)
[RTD page](https://suews.readthedocs.org/en/latest/data-structure/df_state.html)

**Comment by sunt05** [comment]
Thanks @RussellGl - these are indeed inconsistencies brought in due to new developments in the green facet scheme - will fix them this week.

**Comment by sunt05** [comment]
this is an upstream issue which needs the main SUEWS docs to be updated with the development - so a major release of SUEWS would be the solution to this.

**Comment by sunt05** [comment]
Hi @RussellGl this should be fixed now - thanks for reporting the issue!
