### ISSUE TITLE
improve log file treatment

### ISSUE THREAD

**Issue by matthiasdemuzere** [UMEP-dev/SuPy#78]
**Describe the Issue**
When running supy, SuPy.log is created in the directory where the simulation is executed.

This seems to be defined in the [_env.py module](https://github.com/UMEP-dev/SuPy/blob/8319c9063c0b030608f9ad11c591306ce8814f70/src/supy/_env.py).

Is there no option to set another logpath in the beginning @sunt05 ? Or manipulate its filename? As I'd like to keep a log per simulation I do, sensitivity simulations will likely be done at the same time on the same machine. So a more unique log filename or location would be useful.

**Supy version**
supy.__version__: 2022.9.22
supy.__version_driver__: 2021a14.post3

**Is `supy_debug-xxxxxxxx.zip` generated?**
NA

**Screenshots**
NA

**Additional context**
NA

**Comment by sunt05** [comment]
Hi @matthiasdemuzere, I had a go for adding some unique identifier to the log filename, which seemed to be working - would that be enough for you?

**Comment by matthiasdemuzere** [comment]
Hi @sunt05, thanks for this. Having a unique log file per supy session is already a good step forward. 
But since I plan to launch multiple supy runs directly after each other, I think this will not yet work for me?

But no worries, I can probably also do without having separate log files ...

**Comment by sunt05** [comment]
Hi @RussellGl , it seems some clarifications are needed here:
1) log files are mostly to monitor the runtime info: e.g. model speed, diagnostic info regarding the software design, etc.; they are _not_ designed for storing/printing model configurations. 
2) for your purpose, `df_state` is what you might want to look up for such info - ALL model configuration info is stored there.

If you have other questions regarding using `df_state`, feel free to start a new issue to extend this discussion - thanks!

**Comment by sunt05** [comment]
closed as requests have already been dealt with by existing functionalities.
